# Generated by Django 3.1.4 on 2021-02-27 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('no_documento', models.DecimalField(db_column='document_usr', decimal_places=0, max_digits=13, null=True)),
                ('nombre', models.CharField(db_column='f_name', max_length=50)),
                ('apellido', models.CharField(db_column='l_name', max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('no_celular', models.DecimalField(db_column='cell_number', decimal_places=0, max_digits=10, null=True)),
                ('tel_fijo', models.DecimalField(blank=True, db_column='phone', decimal_places=0, max_digits=7, null=True)),
                ('direccion', models.CharField(db_column='address', max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, db_column='neighborhood', max_length=50, null=True)),
                ('referencia_vivienda', models.CharField(blank=True, db_column='home_reference', max_length=50, null=True)),
                ('fecha_cumpleaños', models.DateField(blank=True, db_column='dob', null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('token_key', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True, db_column='register_date', null=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='categorias_servicio',
            fields=[
                ('id_cat_ser', models.AutoField(primary_key=True, serialize=False)),
                ('complemento_servicio', models.CharField(db_column='service_complement', max_length=50)),
                ('descripcion', models.TextField(db_column='description', max_length=250)),
                ('costo', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'plan de servicio',
                'verbose_name_plural': 'planes de servicios',
                'db_table': 'category_services',
            },
        ),
        migrations.CreateModel(
            name='contact_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='name', max_length=40)),
                ('email', models.EmailField(max_length=300)),
                ('cel', models.IntegerField(db_column='celphone', default=0, null=True)),
                ('asunto', models.CharField(max_length=50, null=True)),
                ('mensaje', models.CharField(db_column='message', max_length=600)),
                ('atendida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'db_table': 'contact_request',
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('Fotocopia_cedula', models.BooleanField(db_column='foto_cedula', default=False)),
                ('activo', models.BooleanField(db_column='contract_status', default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_column='registration_date', null=True)),
                ('fecha_inicio_contrato', models.DateField(db_column='start_contract')),
                ('fecha_fin_contrato', models.DateField(db_column='end_contract')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_column='last_modify', null=True)),
                ('cliente', models.ForeignKey(db_column='contract_usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'db_table': 'contratcs',
            },
        ),
        migrations.CreateModel(
            name='descuentos',
            fields=[
                ('id_discount', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_descuento', models.CharField(blank=True, db_column='name_discount', max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=150, null=True)),
                ('condiciones_restricciones', models.CharField(blank=True, db_column='conditions', max_length=80, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=7, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='percentage', decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='estados_plan',
            fields=[
                ('id_state_plan', models.AutoField(primary_key=True, serialize=False)),
                ('estado_plan', models.CharField(blank=True, db_column='name_st', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'estado del plan',
                'verbose_name_plural': 'estados de planes',
                'db_table': 'plan_states',
            },
        ),
        migrations.CreateModel(
            name='estados_usuario',
            fields=[
                ('id_state_usr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='name_st', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'estado del usuario',
                'verbose_name_plural': 'estados de los usuarios',
                'db_table': 'usr_states',
            },
        ),
        migrations.CreateModel(
            name='metodos_pago',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(blank=True, db_column='name_method', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='monto_adicional',
            fields=[
                ('id_amount', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_monto', models.CharField(blank=True, db_column='name_amount', max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=60, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=7, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='percentage', decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'monto adicional',
                'verbose_name_plural': 'montos adicionales',
                'db_table': 'aditional_amount',
            },
        ),
        migrations.CreateModel(
            name='novedades_plan',
            fields=[
                ('id_novel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_novedad', models.CharField(db_column='name_novel', max_length=30)),
                ('descripcion', models.CharField(db_column='description', max_length=100)),
                ('opcional', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='reg_date', null=True)),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades de los planes',
                'db_table': 'novelties',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='name_ser', max_length=50)),
                ('oferta_servicio', models.CharField(db_column='service_offer', max_length=50)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id_ty_us', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(db_column='name_t_u', max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de usuario',
                'verbose_name_plural': 'tipos de usuarios',
                'db_table': 'type_users',
            },
        ),
        migrations.CreateModel(
            name='zonas_servicio',
            fields=[
                ('id_zone', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='name', max_length=40)),
            ],
            options={
                'verbose_name': 'Zona de Servicio',
                'verbose_name_plural': 'Zonas de Servicios',
                'db_table': 'service_zones',
            },
        ),
        migrations.CreateModel(
            name='solicitudes_servicio',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='fname', max_length=60, null=True)),
                ('no_celular', models.DecimalField(blank=True, db_column='cell_phone', decimal_places=0, max_digits=10, null=True)),
                ('tel_fijo', models.DecimalField(blank=True, db_column='phone', decimal_places=0, max_digits=7, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='address', max_length=40, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_column='regis_date', null=True)),
                ('atendido', models.BooleanField(db_column='check_soli', default=False)),
                ('plan', models.ForeignKey(db_column='id_plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categorias_servicio')),
            ],
            options={
                'verbose_name': 'solicitud de servicio',
                'verbose_name_plural': 'solicitudes de servicios',
                'db_table': 'requests_services',
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('dia_inicio_pago', models.IntegerField(choices=[(1, 1), (2, 15)], db_column='start_payment_day', default=1)),
                ('dias_limites_de_pago', models.IntegerField(blank=True, db_column='days_limit', default=5, null=True)),
                ('ip_router', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo_contra', models.DecimalField(db_column='negative_balance', decimal_places=2, default=0, max_digits=10)),
                ('saldo_favor', models.DecimalField(db_column='positive_balance', decimal_places=2, default=0, max_digits=10)),
                ('fecha_instalacion', models.DateTimeField(db_column='instalation_date')),
                ('fecha_registro_plan', models.DateTimeField(auto_now_add=True, db_column='date_start_plan', null=True)),
                ('fecha_fin_plan', models.DateTimeField(db_column='date_end_plan')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, db_column='cancel_plan_date', null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_column='last_modify', null=True)),
                ('contrato', models.ForeignKey(db_column='contract', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.contrato')),
                ('descuentos_adicionales', models.ManyToManyField(blank=True, to='navecomClient.descuentos')),
                ('estado_plan', models.ForeignKey(db_column='state_plan', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.estados_plan')),
                ('montos_adicionales', models.ManyToManyField(blank=True, to='navecomClient.monto_adicional')),
                ('novedades', models.ManyToManyField(blank=True, to='navecomClient.novedades_plan')),
                ('servicio', models.ForeignKey(db_column='id_cat_ser', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categorias_servicio')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes contratados',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.BooleanField(db_column='arrears_state')),
                ('total_recibido', models.DecimalField(blank=True, db_column='balance_received', decimal_places=2, max_digits=9, null=True)),
                ('total_pagar', models.DecimalField(blank=True, db_column='total_pay', decimal_places=2, max_digits=9, null=True)),
                ('total_devuelto', models.DecimalField(blank=True, db_column='balance_returned', decimal_places=2, max_digits=9, null=True)),
                ('codigo_convenio', models.CharField(blank=True, db_column='agreement_code', max_length=50, null=True)),
                ('codigo_epy', models.CharField(blank=True, db_column='epayco_code', max_length=50, null=True)),
                ('pin_epy', models.CharField(blank=True, db_column='epayco_pin', max_length=50, null=True)),
                ('numero_recibo', models.CharField(blank=True, db_column='id_receipt', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='recovery_date', null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, db_column='payment_date', null=True)),
                ('fecha_limite_pago', models.DateTimeField(blank=True, db_column='payday_limit', null=True)),
                ('metodo_pago', models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.metodos_pago')),
                ('plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='entry_date', null=True)),
                ('fecha_despido', models.DateTimeField(blank=True, db_column='dismissal_date', null=True)),
                ('descripcion_cargo', models.CharField(blank=True, db_column='description_work', max_length=100, null=True)),
                ('empleado', models.OneToOneField(db_column='id_employe', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'datos del empleado',
                'verbose_name_plural': 'datos de empleados',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cuenta_pago', models.CharField(blank=True, db_column='payment_account', max_length=50, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='register_date', null=True)),
                ('metodo_pago', models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.metodos_pago')),
                ('usuario', models.OneToOneField(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'datos del cliente',
                'verbose_name_plural': 'datos de los clientes',
                'db_table': 'customers',
            },
        ),
        migrations.AddField(
            model_name='categorias_servicio',
            name='servicio',
            field=models.ForeignKey(db_column='servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.servicio'),
        ),
        migrations.AddField(
            model_name='categorias_servicio',
            name='zonas',
            field=models.ManyToManyField(db_column='zones', to='navecomClient.zonas_servicio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(db_column='state_usr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.estados_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='id_ty_us', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
