# Generated by Django 3.1.4 on 2021-01-10 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('document_usr', models.DecimalField(decimal_places=0, max_digits=13, null=True)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('cell_number', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('home_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('token_key', models.CharField(blank=True, max_length=300, null=True)),
                ('register_date', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AditionalAmount',
            fields=[
                ('id_amount', models.AutoField(primary_key=True, serialize=False)),
                ('name_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'aditional_amount',
            },
        ),
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id_cat_ser', models.AutoField(primary_key=True, serialize=False)),
                ('service_complement', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'category_services',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('contract_status', models.BooleanField()),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('start_contract', models.DateField(blank=True, null=True)),
                ('end_contract', models.DateField(blank=True, null=True)),
                ('contract_usr', models.ForeignKey(db_column='contract_usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratcs',
            },
        ),
        migrations.CreateModel(
            name='CustomStates',
            fields=[
                ('id_state_custom', models.AutoField(primary_key=True, serialize=False)),
                ('name_state', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer_states',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id_discount', models.AutoField(primary_key=True, serialize=False)),
                ('name_discount', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('conditions', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('name_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='PlanStates',
            fields=[
                ('id_state_plan', models.AutoField(primary_key=True, serialize=False)),
                ('name_st', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'plan_states',
            },
        ),
        migrations.CreateModel(
            name='RequestsServices',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=60, null=True)),
                ('cell_phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('regis_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests_services',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('name_ser', models.CharField(max_length=50)),
                ('service_offer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='TypeUsers',
            fields=[
                ('id_ty_us', models.AutoField(primary_key=True, serialize=False)),
                ('name_t_u', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_users',
            },
        ),
        migrations.CreateModel(
            name='UsrStates',
            fields=[
                ('id_state_usr', models.AutoField(primary_key=True, serialize=False)),
                ('name_state', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usr_states',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('instalation_plan', models.DateTimeField(blank=True, null=True)),
                ('start_payment_date', models.DateField(blank=True, null=True)),
                ('end_payment_date', models.DateField(blank=True, null=True)),
                ('cancel_plan_date', models.DateTimeField(blank=True, null=True)),
                ('ip_router', models.CharField(blank=True, max_length=20, null=True)),
                ('contract', models.ForeignKey(db_column='contract', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.contracts')),
                ('contract_usr', models.ForeignKey(db_column='contract_usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_cat_ser', models.ForeignKey(db_column='id_cat_ser', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categoryservices')),
                ('state_plan', models.ForeignKey(db_column='state_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.planstates')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Novelties',
            fields=[
                ('id_novel', models.AutoField(primary_key=True, serialize=False)),
                ('name_novel', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('opcional', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plans')),
            ],
            options={
                'db_table': 'novelties',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('dismissal_date', models.DateTimeField(blank=True, null=True)),
                ('description_work', models.CharField(blank=True, max_length=100, null=True)),
                ('id_employe', models.OneToOneField(db_column='id_employe', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='DiscountList',
            fields=[
                ('id_discount_aply', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(db_column='discount', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.discounts')),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plans')),
            ],
            options={
                'db_table': 'discount_list',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_account', models.CharField(blank=True, max_length=50, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('id_customer', models.OneToOneField(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.paymentmethods')),
                ('state', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.customstates')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.AddField(
            model_name='categoryservices',
            name='id_ser',
            field=models.ForeignKey(db_column='id_ser', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.services'),
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('arrears_state', models.BooleanField()),
                ('positive_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('negative_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('recovery_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payday_limit', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plans')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='AmountList',
            fields=[
                ('id_amount_aply', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.ForeignKey(db_column='amount', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.aditionalamount')),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plans')),
            ],
            options={
                'db_table': 'amount_list',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='id_ty_us',
            field=models.ForeignKey(db_column='id_ty_us', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.typeusers'),
        ),
        migrations.AddField(
            model_name='users',
            name='state_usr',
            field=models.ForeignKey(db_column='state_usr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.usrstates'),
        ),
    ]
