# Generated by Django 3.1.4 on 2021-01-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('no_documento', models.DecimalField(db_column='document_usr', decimal_places=0, max_digits=13, null=True)),
                ('nombre', models.CharField(db_column='f_name', max_length=50)),
                ('apellido', models.CharField(db_column='l_name', max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('no_celular', models.DecimalField(db_column='cell_number', decimal_places=0, max_digits=10, null=True)),
                ('tel_fijo', models.DecimalField(blank=True, db_column='phone', decimal_places=0, max_digits=7, null=True)),
                ('direccion', models.CharField(db_column='address', max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, db_column='neighborhood', max_length=50, null=True)),
                ('referencia_vivienda', models.CharField(blank=True, db_column='home_reference', max_length=50, null=True)),
                ('fecha_cumpleaños', models.DateField(blank=True, db_column='dob', null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('token_key', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True, db_column='register_date', null=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='categorias_servicio',
            fields=[
                ('id_cat_ser', models.AutoField(primary_key=True, serialize=False)),
                ('complemento_servicio', models.CharField(db_column='service_complement', max_length=50)),
                ('descripcion', models.TextField(db_column='description', max_length=100)),
                ('costo', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'category_services',
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('estado_contrato', models.BooleanField(db_column='contract_status')),
                ('fecha_contrato', models.DateTimeField(auto_now=True, db_column='registration_date', null=True)),
                ('fecha_inicio_contrato', models.DateField(blank=True, db_column='start_contract', null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, db_column='end_contract', null=True)),
                ('cliente', models.ForeignKey(db_column='contract_usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contratcs',
            },
        ),
        migrations.CreateModel(
            name='descuentos',
            fields=[
                ('id_discount', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_descuento', models.CharField(blank=True, db_column='name_discount', max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=60, null=True)),
                ('condiciones_restricciones', models.CharField(blank=True, db_column='conditions', max_length=80, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=6, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='percentage', decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='estados_cliente',
            fields=[
                ('id_state_custom', models.AutoField(primary_key=True, serialize=False)),
                ('estado_cliente', models.CharField(blank=True, db_column='name_state', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer_states',
            },
        ),
        migrations.CreateModel(
            name='estados_plan',
            fields=[
                ('id_state_plan', models.AutoField(primary_key=True, serialize=False)),
                ('estado_plan', models.CharField(blank=True, db_column='name_st', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=60, null=True)),
            ],
            options={
                'db_table': 'plan_states',
            },
        ),
        migrations.CreateModel(
            name='estados_usuario',
            fields=[
                ('id_state_usr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='name_st', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
            ],
            options={
                'db_table': 'usr_states',
            },
        ),
        migrations.CreateModel(
            name='metodos_pago',
            fields=[
                ('id_method', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo', models.CharField(blank=True, db_column='name_method', max_length=50, null=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='monto_adicional',
            fields=[
                ('id_amount', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_monto', models.CharField(blank=True, db_column='name_amount', max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=60, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=6, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='percentage', decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'aditional_amount',
            },
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='name_ser', max_length=50)),
                ('oferta_servicio', models.CharField(db_column='service_offer', max_length=50)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id_ty_us', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(db_column='name_t_u', max_length=50)),
            ],
            options={
                'db_table': 'type_users',
            },
        ),
        migrations.CreateModel(
            name='solicitudes_servicio',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='fname', max_length=60, null=True)),
                ('no_celular', models.DecimalField(blank=True, db_column='cell_phone', decimal_places=0, max_digits=10, null=True)),
                ('tel_fijo', models.DecimalField(blank=True, db_column='phone', decimal_places=0, max_digits=7, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='address', max_length=40, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True, db_column='regis_date', null=True)),
                ('plan', models.ForeignKey(db_column='id_plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categorias_servicio')),
            ],
            options={
                'db_table': 'requests_services',
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateTimeField(blank=True, db_column='instalation_date', null=True)),
                ('fecha_inicio_pago', models.DateField(blank=True, db_column='start_payment_date', null=True)),
                ('fecha_limite_pago', models.DateField(blank=True, db_column='end_payment_date', null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, db_column='cancel_plan_date', null=True)),
                ('ip_router', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_plan', models.ForeignKey(db_column='state_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.estados_plan')),
                ('no_contrato', models.ForeignKey(db_column='contract', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.contrato')),
                ('servicio', models.ForeignKey(db_column='id_cat_ser', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categorias_servicio')),
                ('usuario', models.ForeignKey(db_column='contract_usr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='novedades_plan',
            fields=[
                ('id_novel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_novedad', models.CharField(blank=True, db_column='name_novel', max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=100, null=True)),
                ('opcional', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_resgistro', models.DateTimeField(auto_now=True, db_column='reg_date', null=True)),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
            options={
                'db_table': 'novelties',
            },
        ),
        migrations.CreateModel(
            name='lista_montos',
            fields=[
                ('id_amount_aply', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.ForeignKey(db_column='amount', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.monto_adicional')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
            options={
                'db_table': 'amount_list',
            },
        ),
        migrations.CreateModel(
            name='lista_descuentos',
            fields=[
                ('id_discount_aply', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.ForeignKey(db_column='discount', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.descuentos')),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
            options={
                'db_table': 'discount_list',
            },
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('estado_factura', models.BooleanField(db_column='arrears_state')),
                ('saldo_favor', models.DecimalField(db_column='positive_balance', decimal_places=2, max_digits=9)),
                ('saldo_contra', models.DecimalField(db_column='negative_balance', decimal_places=2, max_digits=9)),
                ('total_pagar', models.DecimalField(db_column='total_pay', decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateField(db_column='recovery_date')),
                ('fecha_pago', models.DateField(db_column='payment_date')),
                ('fecha_limite_pago', models.DateField(db_column='payday_limit')),
                ('metodo_pago', models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.metodos_pago')),
                ('plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='entry_date', null=True)),
                ('fecha_despido', models.DateTimeField(blank=True, db_column='dismissal_date', null=True)),
                ('descripcion_cargo', models.CharField(blank=True, db_column='description_work', max_length=100, null=True)),
                ('id_employe', models.OneToOneField(db_column='id_employe', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cuenta_pago', models.CharField(blank=True, db_column='payment_account', max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True, db_column='register_date', null=True)),
                ('estado_cliente', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.estados_cliente')),
                ('id_customer', models.OneToOneField(db_column='id_customer', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(db_column='payment_method', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.metodos_pago')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.AddField(
            model_name='categorias_servicio',
            name='servicio',
            field=models.ForeignKey(db_column='id_ser', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.servicio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(db_column='state_usr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.estados_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='id_ty_us', on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
