# Generated by Django 3.1.4 on 2021-01-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_servicio',
            name='plan',
            field=models.ForeignKey(db_column='id_plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.categorias_servicio'),
        ),
    ]
