# Generated by Django 3.1.4 on 2021-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='pago',
            field=models.BooleanField(db_column='arrears_state', default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fecha_fin_plan',
            field=models.DateTimeField(blank=True, db_column='date_end_plan', null=True),
        ),
    ]
