# Generated by Django 3.1.4 on 2021-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias_servicio',
            options={'verbose_name': 'plan de servicio', 'verbose_name_plural': 'planes de servicios'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.AlterModelOptions(
            name='descuentos',
            options={'verbose_name': 'descuento', 'verbose_name_plural': 'descuentos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='estados_cliente',
            options={'verbose_name': 'estado del cliente', 'verbose_name_plural': 'estados de los clientes'},
        ),
        migrations.AlterModelOptions(
            name='estados_plan',
            options={'verbose_name': 'estado del plan', 'verbose_name_plural': 'estados de planes'},
        ),
        migrations.AlterModelOptions(
            name='estados_usuario',
            options={'verbose_name': 'estado del usuario', 'verbose_name_plural': 'estados de los usuarios'},
        ),
        migrations.AlterModelOptions(
            name='facturas',
            options={'verbose_name': 'factura', 'verbose_name_plural': 'facturas'},
        ),
        migrations.AlterModelOptions(
            name='lista_descuentos',
            options={'verbose_name': 'lista de descuentos', 'verbose_name_plural': 'listas de descuentos'},
        ),
        migrations.AlterModelOptions(
            name='lista_montos',
            options={'verbose_name': 'montoa a plan', 'verbose_name_plural': 'montosa los planes'},
        ),
        migrations.AlterModelOptions(
            name='metodos_pago',
            options={'verbose_name': 'metodo de pago', 'verbose_name_plural': 'metodos de pago'},
        ),
        migrations.AlterModelOptions(
            name='monto_adicional',
            options={'verbose_name': 'monto adicional', 'verbose_name_plural': 'montos adicionales'},
        ),
        migrations.AlterModelOptions(
            name='novedades_plan',
            options={'verbose_name': 'novedades del plan', 'verbose_name_plural': 'novedades de los planes'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'planes'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes_servicio',
            options={'verbose_name': 'solicitud de servicio', 'verbose_name_plural': 'solicitudes de servicios'},
        ),
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name': 'tipo de usuario', 'verbose_name_plural': 'tios de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
