# Generated by Django 3.1.4 on 2021-01-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0002_auto_20210124_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista_montos',
            options={'verbose_name': 'monto del plan', 'verbose_name_plural': 'montos de los planes'},
        ),
    ]
