# Generated by Django 3.1.4 on 2021-03-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0002_auto_20210325_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='direccion_recidencial',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ip_router',
            field=models.CharField(blank=True, db_column='address_plan', max_length=20, null=True),
        ),
    ]
