# Generated by Django 3.1.4 on 2021-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0002_auto_20210227_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_limite_pago',
            field=models.DateTimeField(db_column='payday_limit'),
        ),
    ]
