# Generated by Django 3.1.4 on 2021-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0003_auto_20210325_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='direccion_recidencial',
            field=models.CharField(max_length=300),
        ),
    ]
