# Generated by Django 3.1.4 on 2021-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0003_auto_20210227_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_limite_pago',
            field=models.DateField(db_column='payday_limit', null=True),
        ),
    ]
