# Generated by Django 3.1.4 on 2021-01-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0003_auto_20210124_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'datos del cliente', 'verbose_name_plural': 'datos de los clientes'},
        ),
        migrations.AlterModelOptions(
            name='estados_cliente',
            options={'verbose_name': 'estado del cliente', 'verbose_name_plural': 'estados de los atos de los clientes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name': 'tipo de usuario', 'verbose_name_plural': 'tipos de usuarios'},
        ),
    ]
