# Generated by Django 3.1.4 on 2021-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0004_auto_20210325_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_minima_permanencia',
            field=models.DateField(blank=True, db_column='end_contract', null=True),
        ),
    ]
