# Generated by Django 3.1.4 on 2021-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0004_auto_20210227_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, db_column='payday_limit', null=True),
        ),
    ]
