# Generated by Django 3.1.4 on 2021-01-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0004_auto_20210124_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados_cliente',
            options={'verbose_name': 'estado del cliente', 'verbose_name_plural': 'estados de los clientes'},
        ),
    ]
