# Generated by Django 3.1.4 on 2021-01-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0005_auto_20210124_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'datos del empleado', 'verbose_name_plural': 'datos de empleados'},
        ),
    ]
