# Generated by Django 3.1.4 on 2021-02-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0005_auto_20210227_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='fecha_limite_pago',
        ),
    ]
