# Generated by Django 3.1.4 on 2021-01-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0006_auto_20210124_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_customer',
            new_name='usuario',
        ),
    ]
