# Generated by Django 3.1.4 on 2021-01-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0007_auto_20210125_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='codigo_convenio',
            field=models.CharField(blank=True, db_column='agreement_code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='codigo_epayco',
            field=models.CharField(blank=True, db_column='epayco_code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='numero_recibo',
            field=models.CharField(blank=True, db_column='id_receipt', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='pin_epayco',
            field=models.CharField(blank=True, db_column='epayco_pin', max_length=50, null=True),
        ),
    ]
