# Generated by Django 3.1.4 on 2021-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0007_auto_20210327_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos',
            name='no_meses_aplica',
            field=models.SmallIntegerField(blank=True, db_column='no_aply', default=1, null=True),
        ),
        migrations.AddField(
            model_name='monto_adicional',
            name='no_meses_aplica',
            field=models.SmallIntegerField(blank=True, db_column='no_aply', default=1, null=True),
        ),
    ]
