# Generated by Django 3.1.4 on 2021-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0008_auto_20210328_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='routers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=300)),
                ('ip_dir', models.CharField(max_length=15)),
                ('mascara', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=35)),
                ('mac', models.CharField(max_length=25)),
                ('referencia', models.CharField(max_length=60)),
                ('nuevo', models.CharField(choices=[(1, 'SI'), (2, 'NO')], max_length=3)),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'db_table': 'routers',
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='ip_router',
        ),
    ]
