# Generated by Django 3.1.4 on 2021-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0009_auto_20210202_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, db_column='start_contract'),
        ),
    ]
