# Generated by Django 3.1.4 on 2021-02-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0009_auto_20210202_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='estado_contrato',
            new_name='activo',
        ),
    ]
