# Generated by Django 3.1.4 on 2021-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0010_auto_20210329_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='nuevo',
            field=models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], max_length=3),
        ),
    ]
