# Generated by Django 3.1.4 on 2021-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0011_auto_20210202_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_contrato',
            field=models.DateTimeField(auto_now=True, db_column='registration_date', null=True),
        ),
    ]
