# Generated by Django 3.1.4 on 2021-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0011_auto_20210329_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='router',
        ),
        migrations.AddField(
            model_name='plan',
            name='ip_dir',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='mac',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='marca',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='mascara',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='nuevo',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='referencia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='serial',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.DeleteModel(
            name='routers',
        ),
    ]
