# Generated by Django 3.1.4 on 2021-03-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0012_auto_20210329_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='montos_adicionales',
        ),
    ]
