# Generated by Django 3.1.4 on 2021-02-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0012_auto_20210202_1526'),
        ('navecomClient', '0010_auto_20210203_0050'),
    ]

    operations = [
    ]
