# Generated by Django 3.1.4 on 2021-03-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0013_remove_plan_montos_adicionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='montos_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_aplicado', models.IntegerField(default=0)),
                ('monto_adicional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.monto_adicional')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='montos_adicionales',
            field=models.ManyToManyField(through='navecomClient.montos_plan', to='navecomClient.monto_adicional'),
        ),
    ]
