# Generated by Django 3.1.4 on 2021-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0013_merge_20210203_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'planes contratados'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='days_limit',
            new_name='dias_limites_de_pago',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(db_column='contract_status', default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio_contrato',
            field=models.DateField(db_column='start_contract'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dia_inicio_pago',
            field=models.IntegerField(blank=True, choices=[(1, 30), (2, 15)], db_column='start_payment_day', null=True),
        ),
    ]
