# Generated by Django 3.1.4 on 2021-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0014_auto_20210330_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='montos_adicionales',
            field=models.ManyToManyField(blank=True, through='navecomClient.montos_plan', to='navecomClient.monto_adicional'),
        ),
    ]
