# Generated by Django 3.1.4 on 2021-02-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0014_auto_20210203_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='usuario',
        ),
    ]
