# Generated by Django 3.1.4 on 2021-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0015_remove_plan_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='saldo_contra',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='saldo_favor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='saldo_favor',
            field=models.DecimalField(blank=True, db_column='positive_balance', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='saldo_contra',
            field=models.DecimalField(blank=True, db_column='negative_balance', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, db_column='recovery_date'),
        ),
    ]
