# Generated by Django 3.1.4 on 2021-03-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0015_auto_20210330_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montos_plan',
            name='monto_adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navecomClient.monto_adicional'),
        ),
        migrations.AlterField(
            model_name='montos_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navecomClient.plan'),
        ),
    ]
