# Generated by Django 3.1.4 on 2021-03-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0016_auto_20210330_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montos_plan',
            options={'verbose_name': 'monto del plan', 'verbose_name_plural': 'monstos de los planes'},
        ),
        migrations.AlterModelTable(
            name='montos_plan',
            table='montos_plan',
        ),
    ]
