# Generated by Django 3.1.4 on 2021-02-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0016_auto_20210204_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='saldo_favor',
        ),
        migrations.AddField(
            model_name='plan',
            name='saldo_favor',
            field=models.DecimalField(blank=True, db_column='positive_balance', decimal_places=2, max_digits=10, null=True),
        ),
    ]
