# Generated by Django 3.1.4 on 2021-02-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0017_auto_20210204_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='codigo_epayco',
            new_name='codigo_epy',
        ),
        migrations.RenameField(
            model_name='facturas',
            old_name='pin_epayco',
            new_name='pin_epy',
        ),
        migrations.AddField(
            model_name='facturas',
            name='total_devuelto',
            field=models.DecimalField(blank=True, db_column='balance_returned', decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='total_recibido',
            field=models.DecimalField(blank=True, db_column='balance_received', decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total_pagar',
            field=models.DecimalField(blank=True, db_column='total_pay', decimal_places=2, max_digits=9, null=True),
        ),
    ]
