# Generated by Django 3.1.4 on 2021-03-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0019_auto_20210330_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentos_plan',
            old_name='no_aplicado',
            new_name='no_meses_aplica',
        ),
        migrations.RenameField(
            model_name='montos_plan',
            old_name='no_aplicado',
            new_name='no_meses_aplica',
        ),
    ]
