# Generated by Django 3.1.4 on 2021-03-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0020_auto_20210330_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos_plan',
            name='no_meses_aplica',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='montos_plan',
            name='no_meses_aplica',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
