# Generated by Django 3.1.4 on 2021-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0021_auto_20210204_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, db_column='recovery_date'),
        ),
    ]
