# Generated by Django 3.1.4 on 2021-04-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0021_auto_20210330_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuentos_plan',
            options={'verbose_name': 'descuento del plan', 'verbose_name_plural': 'descuentos adicionales'},
        ),
        migrations.AlterModelOptions(
            name='montos_plan',
            options={'verbose_name': 'monto del plan', 'verbose_name_plural': 'monstos adicionales'},
        ),
    ]
