# Generated by Django 3.1.4 on 2021-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0022_auto_20210204_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, db_column='recovery_date', null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_limite_pago',
            field=models.DateField(db_column='payday_limit', null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_pago',
            field=models.DateField(db_column='payment_date', null=True),
        ),
    ]
