# Generated by Django 3.1.4 on 2021-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0022_auto_20210402_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuentos',
            name='no_meses_aplica',
        ),
        migrations.RemoveField(
            model_name='monto_adicional',
            name='no_meses_aplica',
        ),
        migrations.AlterField(
            model_name='descuentos_plan',
            name='no_meses_aplica',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='montos_plan',
            name='no_meses_aplica',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
