# Generated by Django 3.1.4 on 2021-02-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0023_auto_20210204_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes_servicio',
            name='atendido',
            field=models.BooleanField(db_column='check_soli', default=False),
        ),
    ]
