# Generated by Django 3.1.4 on 2021-04-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0024_auto_20210410_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nuevo',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], default=1),
        ),
    ]
