# Generated by Django 3.1.4 on 2021-04-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0025_auto_20210410_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='ip_dir',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='plan',
            name='mac',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='plan',
            name='marca',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='mascara',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nuevo',
            field=models.IntegerField(choices=[(1, 'SI'), (2, 'NO')], default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='referencia',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='plan',
            name='serial',
            field=models.CharField(max_length=35),
        ),
    ]
