# Generated by Django 3.1.4 on 2021-04-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0027_auto_20210410_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='marca',
            field=models.CharField(default='tenda', max_length=300),
        ),
    ]
