# Generated by Django 3.1.4 on 2021-04-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0028_auto_20210410_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='descuentos',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='montos_adicionales',
        ),
    ]
