# Generated by Django 3.1.4 on 2021-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0029_auto_20210426_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montos_plan',
            options={'verbose_name': 'monto del plan', 'verbose_name_plural': 'montos adicionales para planes'},
        ),
        migrations.AddField(
            model_name='montos_plan',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Culminado')], db_column='estado_monto', default=1, max_length=15),
        ),
    ]
