# Generated by Django 3.1.4 on 2021-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0030_auto_20210426_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuentos_plan',
            options={'verbose_name': 'descuento del plan', 'verbose_name_plural': 'descuentos adicionales para planes'},
        ),
        migrations.AddField(
            model_name='descuentos_plan',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Culminado')], db_column='estado_descuento', default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dia_inicio_pago',
            field=models.IntegerField(choices=[(1, 1), (2, 15)], db_column='start_payment_day'),
        ),
    ]
