# Generated by Django 3.1.4 on 2021-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0032_auto_20210430_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='dia_inicio_pago',
            field=models.CharField(choices=[(1, '1-5'), (2, '15-20')], db_column='start_payment_day', max_length=6),
        ),
    ]
