# Generated by Django 3.1.4 on 2021-05-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0034_auto_20210430_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montos_plan',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('c', 'Culminado')], db_column='estado_monto', default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dia_inicio_pago',
            field=models.CharField(choices=[('1', '1-5'), ('15', '15-20')], db_column='start_payment_day', max_length=6),
        ),
    ]
