# Generated by Django 3.1.4 on 2021-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0035_auto_20210430_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos_plan',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='descuentos_plan',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='pin_payco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='montos_plan',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='montos_plan',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuentos_plan',
            name='estado',
            field=models.CharField(choices=[('p', 'Pendiente'), ('c', 'Culminado')], db_column='descuentos_estado', default=1, max_length=15),
        ),
    ]
