# Generated by Django 3.1.4 on 2021-05-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0036_auto_20210501_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='logsnavecomsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=50)),
                ('log_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'info del sistema',
                'verbose_name_plural': 'informacion del sistema',
                'db_table': 'logsnavecomsystem',
            },
        ),
    ]
