# Generated by Django 3.1.4 on 2021-05-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0037_logsnavecomsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsnavecomsystem',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logsnavecomsystem',
            name='log_description',
            field=models.CharField(max_length=800),
        ),
    ]
