# Generated by Django 3.1.4 on 2021-05-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0038_auto_20210512_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='montos_plan',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.facturas'),
        ),
    ]
