# Generated by Django 3.1.4 on 2021-05-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0039_montos_plan_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos_plan',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='navecomClient.facturas'),
        ),
    ]
