# Generated by Django 3.1.4 on 2021-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0040_descuentos_plan_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='primera_factura',
            field=models.BooleanField(db_column='first_fact', default=0),
        ),
    ]
