# Generated by Django 3.1.4 on 2021-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0041_facturas_primera_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='obsevacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
