# Generated by Django 3.1.4 on 2021-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navecomClient', '0042_facturas_obsevacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='obsevacion',
            new_name='observacion',
        ),
    ]
